# Generated by Django 4.2.1 on 2023-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropDatasetCategory',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=20)),
                ('crop_description', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
